cc_library(
    name = "login_filter",
    hdrs = ["login_filter.h"], 
    srcs = ["login_filter.cc"], 
    deps = [
        "//thirdparty/jwt-cpp:jwt-cpp",
        "//flare/rpc:http",
    ],
    visibility = 'PUBLIC',    
)
