cc_library(
    name = "param_parse",
    hdrs = "param_parse.h",
    srcs = "param_parse.cc",
    visibility = "//cache/..."
)

cc_library(
    name = "leveldb_random",
    hdrs = "random.h",
    srcs = [],
    visibility = "//cache/..."
)

cc_library(
    name = "arena",
    hdrs = "arena.h",
    srcs = ['arena.cc'],
    visibility = "//cache/..."
)
